spring:
  thymeleaf:
    cache: false
    check-template-location: true
    servlet.content-type: text/html
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates
    suffix: .html
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: 1234
    
    
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.demo.entity  